### ISSUE TITLE
Observable Plot option `sort` not available / Static filter support

### ISSUE THREAD

**Issue by spren9er** [uwdata/mosaic#122]
Consider a simple _mosaic_ dashboard based on data from `data/athletes.csv` with a single filter (`selection`) and some plots. Assume one plot should show a ranking of top ten nationalities w.r.t. number of gold medals from female athletes.

```javascript
import * as vg from "@uwdata/vgplot";

await vg.coordinator().exec(
  vg.loadParquet("athletes", "data/athletes.parquet")
);

const selection = Selection.intersect();

export default vg.vconcat(
  vg.menu({
    label: 'Sport',
    from: 'athletes',
    column: 'sport',
    value: 'athletics',
    as: selection
  }),
  vg.plot(
    vg.barX(vg.from('athletes', { filterBy: selection }), {
      x: vg.sum('gold'),
      y: 'nationality',
      sort: {
        y: '-x',
        limit: 10,
      },
    }),
    vg.width(600),
    vg.height(400)
  ),
  // other plots with filter `selection`...
)
```

**Issue 1:** Above code fails. Bars should be sorted (nationality with most gold medals of female athletes on top). However, option `sort` (see [Observable Plot documentation](https://observablehq.com/plot/features/scales#sort-mark-option)) is not detected as Observable Plot mark option.

How to achieve sorting (and limiting) in `vgplot`?

_There seems to be an `order` attribute, which is used on query level, but Observable Plot bars are sorted naturally w.r.t. lexicographical order by default. Using `vg.yDomain` is not an alternative here as domain depends on `selection`._

**Issue 2:** Above plot is missing a filter. For this specific plot only female athletes should be considered. Underlying SQL should look like

```sql
SELECT nationality, SUM(gold) AS gold_medals
FROM 'athletes'
WHERE sex = 'female'       /* static filter (local) */
AND sport = 'athletics'    /* from selection (global) */
GROUP BY nationality
ORDER BY gold_medals DESC
LIMIT 10
```

Is there a _mosaic_ way to express this in `vgplot`?

_I don't want to bypass coordinator logic (run a manual query and pass a data object). Failed with cloning `selection`, extend it and pass extended version to `filterBy`._

**Comment by jheer** [comment]
Thanks for the issue! I think it makes sense to simply pass a `sort` option directly to Plot (at least for basic mark types), providing the desired functionality. As the result affects the scales and visual drawing order, I think it is fine to have sorting options at the plotting (rather than DB query) level here. I've flagged this issue as a feature request to add this support.

I also want to make sure I fully understand issue 2 ("plot missing a filter"). The plot already includes a `filterBy` selection, which includes filtering by sport thanks to the `menu` input. I tested the example and this works as intended. Is the crux of the issue that you also want to include additional filter criteria (in addition to the interactive selection) that is applied to the `barX` mark only? If so, this is not directly supported by vgplot methods, but I might imagine including additional options to the `from(...)` call to support this.

If you want to make the `sex` filter part of the selection, you could add an additional `menu` input or perhaps add a "constant" selection clause via `selection.update`:

```js
selection.update({
  source: 'my-constant',
  predicate: vg.eq('sex', vg.literal('female')),
  value: 'female'
});
```

Alternatively, if you are *only* interested in female athletes you can further prep the data prior to visualization:

```js
vg.loadParquet("athletes", "data/athletes.parquet", { where: `sex = 'female'` })
```

**Comment by spren9er** [comment]
Thanks for prompt response!

**Issue 1:**

>  I've flagged this issue as a feature request to add this support.

Ok, thanks!

**Issue 2:** 

> Is the crux of the issue that you also want to include additional filter criteria (in addition to the interactive selection) that is applied to the `barX` mark only?

Exactly this!

>  If so, this is not directly supported by vgplot methods, but I might imagine including additional options to the `from(...)` call to support this.

That would be great!

Or maybe adding a way to create a _derived selection_, which updates, when `selection` updates (similar to Svelte [derived stores](https://svelte.dev/tutorial/derived-stores)). Above constant `female` clause would be added to this derived selection, which is then passed to `filterBy` in `vg.from` (`barX` mark only). This would also allow to have clause(s) removed in derived selections for specific plots. (Not sure, if it fits in overall concept.)

**Comment by jheer** [comment]
Support for the plot `sort` option has been added in v0.3.2, and is demonstrated here:
https://uwdata.github.io/mosaic/examples/sorted-bars.html

Static filtering is also possible using the plot `filter` option. However, one must make sure that the requisite columns have been loaded. Below the use of the `z` channel ensures the `sex` column is retrieved from the database. In the future, we might add a `detail` (or similar) option to indicate fields that should be retrieved but not otherwise implicated in visual encoding.

```
vg.barX(vg.from('athletes', { filterBy: selection }), {
  x: vg.sum('gold'),
  y: 'nationality',
  z: 'sex', // make sure 'sex' column is queried from the database
  sort: { y: '-x', limit: 10, },
  filter: d => d.sex === 'female' // static filter in Plot, only applicable in JS API (not YAML or JSON)
})
```

We will leave thinking about other filtering configurations that push down to the database for future issues.

**Comment by danielblignaut** [comment]
I'm currently trying to use the filter callback mentioned above however type d is undefined (the first parameter) everytime the function is called.
