### ISSUE TITLE
Readonly mode for duckdb-server

### ISSUE THREAD

**Issue by rgieseke** [uwdata/mosaic#583]
The Python-based `duckdb-server` is very neat and useful!

I was wondering whether it should have duckdb's `readonly` mode as a default, so that you can't drop tables by default.
Is there a way to pass `duckdb` options to `duckdb-server`?

**Comment by domoritz** [comment]
We do need to create materialized views of preaggregated data as tables. If we can enable read only mode for some schemas, that would work, though, since we create the extra tables in a specific schema.

**Comment by rgieseke** [comment]
I see. Probably good to add a note in the Readme (I considered using `duckdb-server` as a public server).

**Comment by jheer** [comment]
In general our philosophy has been to let the developer decide how to configure DuckDB. So I don't think we'd institute any changes at the client-level, but I could imagine providing a helpful configuration option to "lockdown" parts of the database server for better safety.

But as Dominik noted, we typically need write access to (a) load new datasets from files (CSV, Parquet, etc) and (b) to create pre-aggregated data to optimize selection updates (currently written to a dedicated schema, so separable from other tables).

**Comment by domoritz** [comment]
I think a good next step would be to figure out a way to have the pre aggregates in a separate database that can be e.g. in wasm or written to while the data stays in a read-only database. Right now, the server (node, python, or rust) are not designed to be run in a public/untrusted environment since we don't have any kind of protections against SQL attacks.

I'm going to close this issue for now since there is no specific, actionable next step. We could have separate issues for specific design ideas to address the scenario of a public server.

**Comment by rgieseke** [comment]
Thanks for the explanations!
